### ISSUE TITLE
Histograms don't seem to be supported

### ISSUE THREAD

**Issue by davidpdrsn** [miketheman/heroku-buildpack-datadog#14]
I'm using this along with [Shopify's statsd client for ruby](https://github.com/Shopify/statsd-instrument) and trying to measure some histograms, but I'm seeing `Metric type :h not supported on statsd implementation` in the Heroku logs.

I'm not sure how to fix this issue. Any ideas?

**Comment by miketheman** [comment]
I see you've opened https://github.com/Shopify/statsd-instrument/issues/79 - the error message is from that library, not this one. Closing here, and will comment on that issue.
