### ISSUE TITLE
Can't get the agent truly running

### ISSUE THREAD

**Issue by mandysimon88** [miketheman/heroku-buildpack-datadog#15]
Mike,

We are a custom software development firm. We just started using Datadog and are considering integrating it into all of our client projects. But, we’re having some problems getting Datadog up and running on the project we decided to try it out on, which is a Node.js app hosted on Heroku.

We used this Heroku buildpack, which shows up as successfully running when we look at our application logs on Heroku.com. The buildpack installation was successful, and, we can see two processes now running on the Heroku web interface: one for the Agent and one for the app. When we open up logs in the Heroku Dyno terminal, we also see that the agent is running. We even got a screen shot like this in our Datadog account:

![screen shot 2016-04-01 at 11 56 28 am](https://cloud.githubusercontent.com/assets/12855692/14215988/58f80f9c-f814-11e5-82e1-850ffde28d1b.png)

We also were able (only through an external website link) to finally get to the “Metrics Monitoring” page on Datadog, which showed us connected to our app on Heroku:

![screen shot 2016-04-01 at 11 49 53 am](https://cloud.githubusercontent.com/assets/12855692/14215967/3dc9492a-f814-11e5-8ab1-e0841093d8bb.png)

However, once we logged out of our Datadog account and logged back in, we literally cannot get to any other page on the entire Datadog site except this page (and the privacy / TOS docs linked at the bottom of it):

![screen shot 2016-04-01 at 11 50 45 am](https://cloud.githubusercontent.com/assets/12855692/14215981/4c4675c2-f814-11e5-80cb-a2f1e1e9e7ef.png)

We spent almost two hours inside the Heroku Dyno VM, where we were able to see files for the agent, and confirm that it’s running. However, none of the suggested “/agent status” links available on the above Datadog webpage actually worked for us in this environment. 

It seems from the Heroku side that the Agent is running… so what’s the issue? What can we do to get the Agent truly connected to Datadog?

Thanks,

Amanda Simon

**Comment by miketheman** [comment]
Hi @mandysimon88 !

I think this is a question best posed to Datadog Support. Heroku is not a general use case for Datadog, and I think the basic use case to get past the wizard can be done by installing the Agent on your development machine to get past the wizard and activate the product.
