### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by konobi** [miketheman/heroku-buildpack-datadog#16]
Hi there,

Can you verify that this buildpack only works with 2.x ?

**Comment by miketheman** [comment]
The build pack installs the Agent package, which has self-contained
versions of software used.
This means that it should work with any Python version.

Are you having an issue?

**Comment by konobi** [comment]
Yes, I get 
```
~/.apt/opt/datadog-agent $ exec /app/.apt/opt/datadog-agent/embedded/bin/python /app/.apt/opt/datadog-agent/agent/dogstatsd.py start
ImportError: No module named site
```

With `ConnectionRefusedError: [Errno 111] Connection refused` when attempting to connect to statsd.

This is with python-3.5.1 as the python version.

**Comment by miketheman** [comment]
Can you show what version of the Agent package is installed? Also, what
other buildpacks are you running?

**Comment by konobi** [comment]
just heroku/python and agent version datadog-agent 5.7.4

**Comment by miketheman** [comment]
Can you paste the output of `heroku buildpacks` ?

**Comment by konobi** [comment]
```
1. https://github.com/miketheman/heroku-buildpack-datadog.git
2. heroku/python
```

**Comment by miketheman** [comment]
I can confirm and reproduce this behavior with a `runtime.txt` value of "python-3.5.1", and will continue to see what can be done.

**Comment by miketheman** [comment]
It appears that this failure is being induced by the Python buildpack, which [sets some environment variables in the startup profile](https://github.com/heroku/heroku-buildpack-python/blob/0b7a1fc14e6e0a0e694f8e8da1a2e004ef2e53a7/bin/compile#L217-L225) that conflict with path loading.

```shellsession
$ cat .profile.d/python.sh
export PATH=$HOME/.heroku/python/bin:$PATH
export PYTHONUNBUFFERED=true
export PYTHONHOME=/app/.heroku/python
export LIBRARY_PATH=/app/.heroku/vendor/lib:/app/.heroku/python/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=/app/.heroku/vendor/lib:/app/.heroku/python/lib:$LD_LIBRARY_PATH
export LANG=${LANG:-en_US.UTF-8}
export PYTHONHASHSEED=${PYTHONHASHSEED:-random}
export PYTHONPATH=${PYTHONPATH:-/app/}

$ unset PYTHONHOME
$ .profile.d/run-dogstatsd.sh
2016-05-17 12:37:57,462 | INFO | dd.dogstatsd | utils.pidfile(pidfile.py:31) | Pid file is: /app/.apt/opt/datadog-agent/run/dogstatsd.pid
2016-05-17 12:37:57,463 | INFO | dd.dogstatsd | daemon(daemon.py:157) | Starting
2016-05-17 12:37:57,463 | INFO | dd.dogstatsd | daemon(daemon.py:171) | Pidfile: /app/.apt/opt/datadog-agent/run/dogstatsd.pid
```

The reason this works with the Python 2.x runtime is that the `PYTHONHOME` variable is telling the dogstatsd runner to use the buildpack's Python interpreter (2.7.x), and the Agent is using Python 2.7 - so the app and Agent can both can find the `site.py` module on startup.

**Comment by miketheman** [comment]
@konobi I forgot to mention here that the fix for Python 3.x is in, please let me know if you have any issues with that now.
