### ISSUE TITLE
Use native Heroku multi build pack support

### ISSUE THREAD

**Issue by danielcompton** [miketheman/heroku-buildpack-datadog#17]
Heroku now has multi build pack support https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app which makes this a lot simpler. I'm not sure of the exact steps, but it could be good to update the README with the new method available.

**Comment by miketheman** [comment]
Hi @danielcompton ! The docs and install process were updated by @brettlangdon via #13 In January to reflect this procedure.

Can you possibly point out where the mismatch is?

**Comment by danielcompton** [comment]
http://miketheman.github.io/heroku-buildpack-datadog/

**Comment by miketheman** [comment]
Web page has been updated with current README. Thanks for pointing it out!
