### ISSUE TITLE
Can't install datadog-agent

### ISSUE THREAD

**Issue by jclif** [miketheman/heroku-buildpack-datadog#2]
When I push to heroku, I get the following error:

Fetching repository, done.
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 285 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)

```
-----> Fetching custom git buildpack... done
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/miketheman/heroku-buildpack-datadog.git
=====> Detected Framework: Heroku Datadog Buildpack
-----> Updating apt caches
       Ign http://apt.datadoghq.com stable InRelease
       Get:1 http://apt.datadoghq.com stable Release.gpg [473 B]
       Hit http://apt.datadoghq.com stable Release
       Ign http://apt.datadoghq.com stable Release
       Ign http://apt.datadoghq.com stable/main amd64 Packages/DiffIndex
       Hit http://apt.datadoghq.com stable/main amd64 Packages
       Ign http://apt.datadoghq.com stable/main Translation-en
       Fetched 473 B in 1s (442 B/s)
       Reading package lists...
W: GPG error: http://apt.datadoghq.com stable Release: The following signatures couldn't be verified because the public key is not avail
able: NO_PUBKEY 226AE980C7A7DA52
-----> Fetching datadog-agent
       Reading package lists...
       Building dependency tree...
       The following NEW packages will be installed:
         datadog-agent
       0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
       Need to get 0 B/55.8 MB of archives.
       After this operation, 177 MB of additional disk space will be used.
       WARNING: The following packages cannot be authenticated!
         datadog-agent
       Download complete and in download only mode
-----> Fetching deb packages
-----> Installing datadog-agent_1%3a5.3.0-1_amd64.deb
-----> Datadog Agent package installed
Using release configuration from last framework (Heroku Datadog Buildpack).
-----> Discovering process types
       Procfile declares types -> web, worker
```

**Comment by miketheman** [comment]
Is this an error? It looks like a Warning to me. The package is downloaded and then installed correctly - we can try to look at solving the warning issue.

**Comment by jclif** [comment]
Oops, sorry, it does seem to be installing correctly. Should I be able to see the process running via 'heroku ps'? I'm trying to use this with a rails application but the web process specified in my Procfile seems to be crashing.

**Comment by jclif** [comment]
Sorry again, adding the ruby buildpack seems to have fixed the crashing issue, but I still haven't been able to confirm that the process is running within heroku.

**Comment by miketheman** [comment]
I just tried using the most recent code in the example https://github.com/miketheman/buildpack-example-ruby

Here's what you should expect to see via `heroku logs`:
```
...
2015-05-02T17:58:50.226853+00:00 app[web.1]: Log file is unwritable: '/var/log/datadog/dogstatsd.log'
2015-05-02T17:58:50.444485+00:00 app[web.1]: 2015-05-02 17:58:50,444 | INFO | dd.dogstatsd | daemon(daemon.py:173) | Pidfile: /tmp/dogstatsd.pid
2015-05-02T17:58:50.444387+00:00 app[web.1]: 2015-05-02 17:58:50,444 | INFO | dd.dogstatsd | daemon(daemon.py:160) | Starting
...
```

There won't be any output after that. You can verify if packets are being sent via statsd from your app by exploring the metric here:
https://app.datadoghq.com/metric/explorer?live=true&exp_metric=datadog.dogstatsd.packet.count&exp_scope=&exp_group=host&exp_agg=avg&exp_row_type=metric

**Comment by gautam-soni** [comment]
Whats the hostname you pass in to submit metrics from your dyno, once you enable the datadog? I tried "localhost" it doesnt seem to work.

**Comment by miketheman** [comment]
@gautam-soni While that's a different question than the one started in this issue, here's the code that prompts the user to set a hostname:
https://github.com/miketheman/heroku-buildpack-datadog/blob/master/extra/run-dogstatsd.sh#L10-L15

Once you set the environment variable and redeploy, you should see metrics tagged with the heroku app name.

**Comment by miketheman** [comment]
@jclif Have you been able to confirm, or find some more debug info?

**Comment by miketheman** [comment]
@jclif Closing this, as I haven't heard back from you. If it's still an issue, please respond and reopen the case with more details.
