### ISSUE TITLE
As of today this stopped working for us 

### ISSUE THREAD

**Issue by mnewell** [miketheman/heroku-buildpack-datadog#20]
Hi,

As of today, all of our Heroku apps (Java Play 1.x) that use this buildpack have stopped reporting to Heroku. (All of our Heroku apps have been rereleased in the last few days). Although the dogstatsd daemon is running in the dyno, and I can feed it dummy metrics via nc, those never show up at datadog. 

```bash
~ $ ps -ef | grep datadog
u5200       11     1  0 21:01 ?        00:00:02 /app/.apt/opt/datadog-agent/embedded/bin/python /app/.apt/opt/datadog-agent/agent/do
~ $ echo -n "toast.fakemetric:1|g|#shell" | nc 127.0.0.1 8125
```
How can I better troubleshoot this issue?

**Comment by miketheman** [comment]
Hi @mnewell ! So sorry you're hitting a problem.

It appears that you're using `nc` to send tcp (default) packets. You can confirm via:

```
~ $ echo -n "toast.fakemetric:1|g|#shell" | nc -u 127.0.0.1 8125
^C # this will hang forever until you Ctrl+C out
# or:
~ $ echo -n "toast.fakemetric:1|g|#shell\n" | socat - udp-sendto:127.0.0.1:8125
```

Either of these should confirm connectivity is still there.

**Comment by mnewell** [comment]
Thanks for the rapid response, @miketheman .

Yes, well, this is the weird thing -- dogstatsd is listening on tcp, not udp, even though I knew that it was supposed to listen on udp. So I was trying to send using tcp. Again from a dyno bash:

```
~ $ ss -lp | grep 8125
tcp    UNCONN     0      0         ::ffff:127.0.0.1:ipproto-8125              :::*        users:(("python",11,4))
```

**Comment by miketheman** [comment]
@mnewell This appears to be a [bug in how ss reports Netid](http://git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git/commit/?id=77a8ca81189197e8d5e75fe19951efd0aea337d5).

You can confirm that the socket is listening on UDP by passing the `-u` flag:
```
~ $ ss -lpu | grep 8125
UNCONN     0      0        ::ffff:127.0.0.1:8125                    :::*        users:(("python",11,4))
```

**Comment by mnewell** [comment]
Wow, you're right! Thanks so much for pointing me in the right direction; it looks pretty clear now that the problem must be in our application, not the dogstatsd configuration. Sending a metric to dogstatsd on udp works. I did look at dogstatsd.py and couldn't conceive of how it would ever be listening on tcp; thanks again.

**Comment by backus** [comment]
Not sure if this is related, but we had issues (triggering [Incident 971](https://status.heroku.com/incidents/971)) with this buildpack today also due to heroku unsetting (and not letting us reconfigure) `HEROKU_APP_NAME`. Looks like heroku just fixed the issue now

**Comment by mnewell** [comment]
@backus Yeah, that bit us too (not in production, thank god...); Heroku still hasn't fixed it definitively yet. Can set that env var, Heroku claims to be creating a new version, but then the env var never shows up.

**Comment by backus** [comment]
@mnewell no promises but try out `heroku labs:enable runtime-dyno-metadata`

**Comment by alainmeier** [comment]
@mnewell After enabling the labs flag  you should trigger a slug rebuild by making a junk env var

**Comment by miketheman** [comment]
Glad to hear the collaboration on getting things back online! Closing this question, please reopen if this particular incident resurfaces, or open a new one with further details.
