### ISSUE TITLE
What to pass in as host for DataDogDClient?

### ISSUE THREAD

**Issue by gautam-soni** [miketheman/heroku-buildpack-datadog#3]
Sorry, I just updated on the other thread. My question is, I use com.timgroup.statsd.NonBlockingStatsDClient in my app to push my metrics, but I dont know the host:port on which to setup this connection. I got DataDog started alongside my dyno, by using this buildpack. The port I believe would be 18125, but what to pass in as host. 
As you said, I should pick it up from env variable, but which one?

**Comment by miketheman** [comment]
@gautam-soni thanks for digging further.
The dogstatsd service should be started on port 8125 on localhost.

Did you find the port 18125 somewhere in the notes/docs? That's likely a mistake.

Here's an example connection string for a Ruby app: https://github.com/miketheman/buildpack-example-ruby/blob/master/app.rb#L6

**Comment by miketheman** [comment]
@gautam-soni Never heard back from you here. If you have more details, pleas reopen with them.
