### ISSUE TITLE
Can be possible to change dd-agent port?

### ISSUE THREAD

**Issue by abtris** [miketheman/heroku-buildpack-datadog#5]
I can try use `80` or `443` for send metrics from another heroku app.

**Comment by miketheman** [comment]
The buildpack is meant to be run inside a dyno, alongside the application.

Can you describe why you'd want to run this alone? We had not designed this to be a aggregator from multiple external sources - one reason is that if we open the listener to port 80/433, _anyone_ could submit metrics to your endpoint and account.

**Comment by abtris** [comment]
I can replace Hosted Graphite with Datadog and integration with Heroku is hard. Hosted graphite have possibility send `statsd` directly to service but Datadog not.

**Comment by miketheman** [comment]
I'm going to close out this issue, as the intent of this buildpack is to enable a locally running statsd agent that forwards packets along from the locally running application, not as a relay-only process - this has other implications around application security, app name traceability and others that I cannot think of right now.

This buildback was designed to be simple to start using - add to your current app's buildpacks and then redeploy. If that's not working out, please let me know.
