### ISSUE TITLE
Logfile is unwritable - crash

### ISSUE THREAD

**Issue by squarism** [miketheman/heroku-buildpack-datadog#7]
On boot/deploy my process crashes because this log file is on a read-only filesystem.

```
INFO | dd.dogstatsd | utils.pidfile(pidfile.py:31) | Pid file is: /app/.apt/opt/datadog-agent/run/dogstatsd.pid
INFO | dd.dogstatsd | daemon(daemon.py:160) | Starting
INFO | dd.dogstatsd | daemon(daemon.py:173) | Pidfile: /app/.apt/opt/datadog-agent/run/dogstatsd.pid
2015-11-03T19:33:57.049332+00:00 app[worker.1]: bash: bundle: command not found
2015-11-03T19:33:56.901154+00:00 app[worker.1]: Log file is unwritable: '/var/log/datadog/dogstatsd.log'
```

Do I need to explicitly add the ruby buildpack?  This dyno doesn't know what `bundle` is even though it's a rails app.  Weird.  I guess heroku handles the gem installs.  I'm going to keep working on this an update ...

**Comment by miketheman** [comment]
@squarism I believe that you have to apply the correct buildpacks. It's been a while since I touched this, so the buildpack methods on heroku might have a changed a bit...

Looking forward to what you come up with!

**Comment by squarism** [comment]
The `mkdir` from the PR merged in this issue fixed the problem I mentioned above.  Thank you!

**Comment by miketheman** [comment]
@squarism Glad to hear it! Kudos belong to @stringbean !
